export const SYSTEM_LABELS: Record<string, string> = {
  roof: "Roof",
  hvac: "HVAC",
  plumbing: "Plumbing",
  electrical: "Electrical",
  water_heater: "Water heater",
  foundation: "Foundation",
};

export const URGENCY_LABELS: Record<string, string> = {
  next_90_days: "Next 90 days",
  next_2_years: "Next 2 years",
  next_5_years: "Next 5 years",
};

// Roadmap display order -- most urgent first. Matches the order the backend
// already sorts action items into (see extraction/service.py).
export const URGENCY_TIERS = ["next_90_days", "next_2_years", "next_5_years"] as const;

// Generic industry rule-of-thumb lifespans in years, [low, high]. Not derived
// from any report or from this specific unit's make/model/condition -- purely
// a reference range for a typically maintained system of that type. Always
// label UI using this as "typical", never as a measurement or a prediction
// specific to the home being reported on.
export const TYPICAL_LIFESPAN_YEARS: Record<string, [number, number]> = {
  roof: [20, 25],
  hvac: [15, 20],
  plumbing: [40, 70],
  electrical: [30, 40],
  water_heater: [8, 12],
  foundation: [80, 100],
};

// Semantic tone per system condition -- kept separate from the accent color
// (see the visual identity proposal). Tailwind class strings are written out
// in full so the compiler's content scan picks them up.
export const CONDITION_TONE: Record<string, { pill: string; fill: string }> = {
  excellent: { pill: "bg-sage-soft text-sage", fill: "bg-sage" },
  good: { pill: "bg-sage-soft text-sage", fill: "bg-sage" },
  fair: { pill: "bg-ochre-soft text-ochre", fill: "bg-ochre" },
  poor: { pill: "bg-brick-soft text-brick", fill: "bg-brick" },
  not_mentioned: { pill: "bg-surface-sunk text-ink-faint", fill: "bg-ink-faint" },
};

// Action-oriented labels, not verdicts -- mirrors the SER/MM/RR/NI legend
// printed on the inspection reports ALYF ingests (see e.g. tests-reports),
// rather than inventing new wording. A bare "Poor" reads as a grade handed
// down on the whole system before a reader gets to any context; naming the
// next step instead keeps the same information without the courtroom tone.
export const CONDITION_LABEL: Record<string, string> = {
  excellent: "Serviceable",
  good: "Serviceable",
  fair: "Monitor",
  poor: "Repair or Replace",
  not_mentioned: "Not Assessed",
};

// Deliberately separate from CONDITION_TONE/CONDITION_LABEL: a system can be
// "Poor" for a routine, non-urgent reason (an aging roof) or for a genuine
// life-safety reason (a furnace with flame roll-out). Condition and urgency
// tier alone don't distinguish those, so this flags anything whose own
// wording already names a hazard -- keyword matching against the AI's
// generated text, not a verified backend classification. It only ever adds
// a stronger flag on top of the existing signals; it never softens anything.
const SAFETY_HAZARD_TERMS = [
  "safety concern",
  "safety hazard",
  "safety issue",
  "unsafe",
  "hazard",
  "carbon monoxide",
  "combustion problem",
  "combustion issue",
  "flame roll-out",
  "flame rollout",
  "gas leak",
  "shock risk",
  "shock hazard",
  "electrocution",
  "fire risk",
  "fire hazard",
  "explosion",
  "structural failure",
  "structural collapse",
  "life safety",
  "life-safety",
];

export function isSafetyHazard(...texts: (string | null | undefined)[]): boolean {
  const combined = texts.filter(Boolean).join(" ").toLowerCase();
  return SAFETY_HAZARD_TERMS.some((term) => combined.includes(term));
}

// A bare decimal ("0.60") asks a homeowner to have an intuition for what
// counts as high or low. A word doesn't -- the raw number stays available
// via a tooltip for anyone who wants it (see ConfidenceGauge).
export function confidenceLabel(value: number): "High" | "Medium" | "Low" {
  if (value >= 0.75) return "High";
  if (value >= 0.5) return "Medium";
  return "Low";
}

export function formatCostRange(low: number, high: number): string {
  const fmt = (value: number) => `$${value.toLocaleString()}`;
  return low === high ? fmt(low) : `${fmt(low)} – ${fmt(high)}`;
}

// Placeholder copy, not legal advice -- flag for real legal review before
// launch. Kept here so the report pages and the reminder-email builder
// (backend/app/notifications/service.py has its own copy of the cost line,
// since Python and TypeScript can't share a constant) stay worded the same.
export const COST_DISCLAIMER =
  "Cost estimates are AI-generated general ranges, not quotes, and have not been " +
  "independently verified. They are not part of the inspector's findings or " +
  "professional opinion. Have a licensed contractor confirm scope and cost before " +
  "making repair decisions.";

export function reportDisclaimer(inspectorName: string | null): string {
  const name = inspectorName ? `${inspectorName}'s` : "your inspector's";
  return (
    `This summary was generated by AI from ${name} original inspection report and is ` +
    "provided for convenience only. It is not a substitute for the full inspection report. " +
    "In the event of any conflict between this summary and the original report, the " +
    "original report governs."
  );
}

export const EVENT_STATUS_LABEL: Record<string, string> = {
  pending_review: "Pending review",
  approved: "Approved",
  auto_sent: "Auto-sent",
};
